export const abbreviatedNames = {
	'Arsenal': 'ARS',
	'Aston Villa': 'AVL',
	'Bournemouth': 'BOU',
	'Brentford': 'BRE',
	'Brighton and Hove Albion': 'BHA',
	'Burnley': 'BUR',
	'Chelsea': 'CHE',
	'Crystal Palace': 'CRY',
	'Everton': 'EVE',
	'Fulham': 'FUL',
	'Leeds United': 'LEE',
	'Liverpool': 'LIV',
	'Manchester City': 'MCI',
	'Manchester United': 'MUN',
	'Newcastle United': 'NEW',
	'Nottingham Forest': 'NFO',
	'Sunderland': 'SUN',
	'Tottenham Hotspur': 'TOT',
	'West Ham United': 'WHU',
	'Wolverhampton Wanderers': 'WOL'
};